name: Build mkmoonworld for ARM

on: [push, pull_request]

jobs:
  build:
    name: Build on ARM
    runs-on: ubuntu-latest
    env:
      CC: aarch64-linux-gnu-gcc
      CXX: aarch64-linux-gnu-g++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'xkx2021/mkmoonworld'
        path: 'mkmoonworld'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Compile mkmoonworld
      working-directory: ./mkmoonworld
      run: |
        ./buildmoon.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mkmoonworld-binary
        path: mkmoonworld/mkmoonworld-arm
